### ISSUE TITLE
Addon won't login if PassIFox (KeePassHTTP for firefox/OSX) is installed

### ISSUE THREAD

**Issue by nederdirk** [VoIPGRID/firefox-addon#38]
The VoIPGRID addon won't login on my computer (OS X 10.11 El Capitan, Firefox 51, MacPass (with KeePassHTTP plugin), PassIFox firefox addon for autofilling passwords from MacPass)

After I fill email address and password and submit the form, MacPass notifies a KeePassHTTP password request for `partner.voipgrid.nl` and then the plugin clears the username/password field and seems to crash completely. No login HTTP request seems to leave my machine.

Disabling the PassIFox addon makes the VoIPGRID addon work properly again.
I would certainly accept a suggestion for another KeePassHTTP addon as a solution, given that addon provides autocomplete for multiple names/passwords per site.

**Comment by ghost** [comment]
Sorry for the extreme late reply. PassIFox is  written in legacy code and will not be usable from FF 57 on. We refactored our plugin into a codebase that builds for multiple browser and vendor targets(https://github.com/VoIPGRID/vialer-js). The same issue probably applies, but for now I'm closing it, due to the legacy nature of PassIFox.
